<a href="https://colab.research.google.com/github/hajyhia/Airbnb_Berlin_Price_predic/blob/main/05_Airbnb_Berlin_Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install missingno
# !pip install geopy

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
# from pandas_profiling import ProfileReport
import numpy as np
import missingno as msno
sns.set()
# plt.style.use('ggplot')
plt.style.use('seaborn-v0_8')
import warnings
import datetime as dt

from sklearn import ensemble, tree, linear_model
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

from scipy.stats import pearsonr
from scipy.stats import ks_2samp
from scipy.stats import norm
from scipy import stats
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway

# Ignore warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df_Feature_Engineering = pd.read_pickle('/content/drive/My Drive/Airbnb/df_Feature_Engineering.pkl')

## Declare data columns Lists

In [5]:
# numerical_columns = ['Accomodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Guests Included','Min Nights','Reviews','Price']
# rating_columns = ['Value Rating','Location Rating', 'Cleanliness Rating','Checkin Rating','Accuracy Rating','Communication Rating','Host Response Rate','Overall Rating']
# boolean_columns = ['Is Superhost','Is Exact Location', 'Instant Bookable']
# categorical_columns = ['Room Type','Property Type Reduced','Neighborhood Group','Postal Code Reduced','Host Response Time'] # , 'Neighbourhood Grouped'
# categorical_encoded_columns = ['Room Type Encoded','Property Type Reduced Encoded','Neighborhood Group Encoded','Postal Code Reduced Encoded','Host Response Time Encoded']
# date_columns = ['review_date','Host Since']
# geo_columns = ['Latitude','Longitude']
# num_non_dummy_columns = numerical_columns + rating_columns + categorical_encoded_columns + geo_columns

# Feature Selection

In [6]:
df_Feature_Selection = pd.read_pickle('/content/drive/My Drive/Airbnb/df_Feature_Selection.pkl')
df_Feature_Selection.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23536 entries, 0 to 23535
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Accuracy Rating               23536 non-null  float64
 1   Bathrooms                     23536 non-null  float64
 2   Checkin Rating                23536 non-null  float64
 3   Cleanliness Rating            23536 non-null  float64
 4   Communication Rating          23536 non-null  float64
 5   Latitude                      23536 non-null  float64
 6   Location Rating               23536 non-null  float64
 7   Longitude                     23536 non-null  float64
 8   Overall Rating                23536 non-null  float64
 9   Price                         23536 non-null  float64
 10  Value Rating                  23536 non-null  float64
 11  Comments                      23536 non-null  object
 12  Host Since                    23515 non-null  datetime64[ns]
 13  Host Response Time            23536 non-null  object
 14  Is Superhost                  23536 non-null  bool
 15  neighbourhood                 23536 non-null  object
 16  Neighborhood Group            23536 non-null  object
 17  Postal Code                   23536 non-null  object
 18  Is Exact Location             23536 non-null  bool
 19  Property Type                 23536 non-null  object
 20  Room Type                     23536 non-null  object
 21  Instant Bookable              23536 non-null  bool
 22  Accomodates                   23536 non-null  float64
 23  Bedrooms                      23536 non-null  float64
 24  Beds                          23536 non-null  float64
 25  Guests Included               23536 non-null  float64
 26  Min Nights                    23536 non-null  float64
 27  Reviews                       23536 non-null  float64
 28  Property Type Reduced         23536 non-null  object
 29  Postal Code Reduced           23536 non-null  object
 30  Distance From Center          23536 non-null  float64
 31  Distance From Center Reduced  23536 non-null  category
 32  Host Since Year               23515 non-null  category
 33  Host Since From Now           23536 non-null  int64
dtypes: bool(3), category(2), datetime64[ns](1), float64(18), int64(1), object(9)
memory usage: 5.3+ MB

In [7]:
df_Feature_Selection['Distance From Center Reduced']

0         km_4
1         km_2
2         km_4
3         km_2
4         km_4
         ...
23531    km_25
23532    km_25
23533     km_4
23534    km_25
23535     km_8
Name: Distance From Center Reduced, Length: 23536, dtype: category
Categories (9, object): ['km_0' < 'km_0.5' < 'km_1' < 'km_2' ... 'km_8' < 'km_10' < 'km_12' < 'km_25']

In [8]:
df = df_Feature_Selection.copy()

In [9]:
df = df.drop(columns=['Host Since','Host Since Year', 'Postal Code', 'Property Type', 'Comments','neighbourhood',
                      'Distance From Center', 'Longitude', 'Latitude'], inplace=False)

## One-Hot Enciding and Label Encoding

In [10]:
from sklearn.preprocessing import OrdinalEncoder

df_object =  df.select_dtypes(include = ['object','category']).columns
for col in df_object:
  ord_enc = OrdinalEncoder()
  df[[col]] = ord_enc.fit_transform(df[[col]]).astype('int')

In [11]:
df.head(2)

,Accuracy Rating,Bathrooms,Checkin Rating,Cleanliness Rating,Communication Rating,Location Rating,Overall Rating,Price,Value Rating,Host Response Time,Is Superhost,Neighborhood Group,Is Exact Location,Room Type,Instant Bookable,Accomodates,Bedrooms,Beds,Guests Included,Min Nights,Reviews,Property Type Reduced,Postal Code Reduced,Distance From Center Reduced,Host Since From Now
0,10.0,1.0,10.0,10.0,10.0,9.0,100.0,17.0,10.0,2,False,6,True,1,False,2.0,1.0,1.0,1.0,2.000000,7.0,0,0,7,17
1,9.0,1.0,9.0,9.0,9.0,10.0,92.0,90.0,9.0,2,False,6,True,0,False,4.0,1.0,2.0,2.0,1.727273,144.0,0,0,5,17

## Multivariable Analysis

In [12]:
#Creating Variables dataframeS
varSel = pd.DataFrame({'Variable': df.columns.drop('Price')})
varSel

                        Variable
0                Accuracy Rating
1                      Bathrooms
2                 Checkin Rating
3             Cleanliness Rating
4           Communication Rating
5                Location Rating
6                 Overall Rating
7                   Value Rating
8             Host Response Time
9                   Is Superhost
10            Neighborhood Group
11             Is Exact Location
12                     Room Type
13              Instant Bookable
14                   Accomodates
15                      Bedrooms
16                          Beds
17               Guests Included
18                    Min Nights
19                       Reviews
20         Property Type Reduced
21           Postal Code Reduced
22  Distance From Center Reduced
23           Host Since From Now

In [13]:
df.to_csv('/content/drive/My Drive/Airbnb/df_Feature_Selection.csv')

In [14]:
nm = df.columns.drop('Price')
nm = nm.append(pd.Index(['Price']))
nm

Index(['Accuracy Rating', 'Bathrooms', 'Checkin Rating', 'Cleanliness Rating',
       'Communication Rating', 'Location Rating', 'Overall Rating',
       'Value Rating', 'Host Response Time', 'Is Superhost',
       'Neighborhood Group', 'Is Exact Location', 'Room Type',
       'Instant Bookable', 'Accomodates', 'Bedrooms', 'Beds',
       'Guests Included', 'Min Nights', 'Reviews', 'Property Type Reduced',
       'Postal Code Reduced', 'Distance From Center Reduced',
       'Host Since From Now', 'Price'],
      dtype='object')

In [15]:
df2 = df[nm].copy()

In [16]:
df2 = df2.dropna()
X = df.drop(columns='Price', inplace=False)
y = df['Price']

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVR
from sklearn.linear_model import Ridge

### Variable Selection using LASSO (L1 penalization)

In [18]:
lassomod = Lasso(alpha=0.01).fit(X, y)
model = SelectFromModel(lassomod, prefit=True)
# print(f"get_support: {model.get_support()}")
# print(f"coef: {lassomod.coef_}")
varSel['Lasso'] = model.get_support().astype('int64')

### Variable Selection using Ridge

In [19]:
ridge = Ridge(alpha=5).fit(X, y)
model = SelectFromModel(ridge, prefit=True)
# print(f"get_support: {model.get_support()}")
# print(f"coef: {ridge.coef_}")
varSel['Ridge'] = model.get_support().astype('int64')

In [20]:
alpha_values = np.logspace(-1, 1, 10)  # 10 values between 10^-4 and 10^4

In [21]:
alpha_values

array([ 0.1       ,  0.16681005,  0.27825594,  0.46415888,  0.77426368,
        1.29154967,  2.15443469,  3.59381366,  5.9948425 , 10.        ])

In [22]:
from sklearn.linear_model import RidgeCV

# RidgeCV automatically finds the best alpha
ridge_cv = RidgeCV(alphas=alpha_values, store_cv_values=True)
ridge_cv.fit(X, y)

# Print the best alpha
print(f"Best alpha: {ridge_cv.alpha_}")

Best alpha: 10.0

### Variable Selection using Gradient Boosting classification

In [23]:
gbmod = GradientBoostingRegressor().fit(X, y)
model = SelectFromModel(gbmod , prefit=True)
# print(f"get_support: {model.get_support()}")
# print(f"coef: {gbmod.coef_}")
varSel['GradientBoost'] = model.get_support().astype('int64')

### Variable Selection using Random Forest

In [24]:
rfmod = RandomForestRegressor().fit(X, y)
model = SelectFromModel(rfmod, prefit=True)
# print(f"get_support: {model.get_support()}")
# print(f"coef: {rfmod.coef_}")
varSel['RandomForest'] = model.get_support().astype('int64')

### Summarization and Selection of Variables

In [25]:
varSel['Sum'] = varSel[['Lasso', 'Ridge', 'GradientBoost','RandomForest']].sum(axis=1)
varSel

,Variable,Lasso,Ridge,GradientBoost,RandomForest,Sum
0,Accuracy Rating,1,1,1,1,4
1,Bathrooms,0,0,0,0,0
2,Checkin Rating,1,1,0,0,2
3,Cleanliness Rating,1,0,1,1,3
4,Communication Rating,1,0,0,0,1
5,Location Rating,1,1,0,0,2
6,Overall Rating,1,0,1,0,2
7,Value Rating,1,0,0,0,1
8,Host Response Time,1,0,0,0,1
9,Is Superhost,1,0,0,0,1
10,Neighborhood Group,1,0,0,0,1
11,Is Exact Location,1,1,0,0,2
12,Room Type,1,1,0,0,2
13,Instant Bookable,1,1,0,0,2
14,Accomodates,1,0,0,0,1
15,Bedrooms,1,1,0,0,2
16,Beds,1,0,0,0,1
17,Guests Included,1,1,0,0,2
18,Min Nights,1,0,0,0,1
19,Reviews,1,0,0,0,1
20,Property Type Reduced,1,1,1,1,4
21,Postal Code Reduced,1,0,0,0,1
22,Distance From Center Reduced,1,0,0,0,1
23,Host Since From Now,1,0,1,0,2

In [26]:
varSel.to_csv('/content/drive/My Drive/Airbnb/Feature_Selection_models.csv')

In [27]:
varSel.shape

(24, 6)

In [28]:
varSel[['Variable', 'Sum']].sort_values(by='Sum', ascending=False)

                        Variable  Sum
0                Accuracy Rating    4
20         Property Type Reduced    4
3             Cleanliness Rating    3
2                 Checkin Rating    2
6                 Overall Rating    2
13              Instant Bookable    2
11             Is Exact Location    2
5                Location Rating    2
17               Guests Included    2
23           Host Since From Now    2
12                     Room Type    2
15                      Bedrooms    2
14                   Accomodates    1
7                   Value Rating    1
4           Communication Rating    1
10            Neighborhood Group    1
19                       Reviews    1
8             Host Response Time    1
9                   Is Superhost    1
16                          Beds    1
21           Postal Code Reduced    1
18                    Min Nights    1
22  Distance From Center Reduced    1
1                      Bathrooms    0

In [29]:
varSel[varSel['Sum'] >=1].shape

(23, 6)

## Multivariable Analysis

In [30]:
# Fit models and determine if a feature is selected (1) or not (0)
lasso = Lasso(alpha=5).fit(X, y)
lasso_selected = (np.abs(lasso.coef_) > 0).astype(int)

# Fit Ridge model
ridge = Ridge(alpha=5).fit(X, y)
ridge_selected = (np.abs(ridge.coef_) > 0).astype(int)

gb = GradientBoostingRegressor().fit(X, y)
gb_selected = (gb.feature_importances_ > 0).astype(int)

rf = RandomForestRegressor().fit(X, y)
rf_selected = (rf.feature_importances_ > 0).astype(int)

# Create a DataFrame to store results
selection_df = pd.DataFrame({
    'Feature': X.columns,
    'Lasso': lasso_selected,
    'GradientBoost': gb_selected,
    'RandomForest': rf_selected,
    'Ridge': ridge_selected
})

# Sum the number of selections for each feature
selection_df['Sum'] = selection_df[['Lasso', 'GradientBoost', 'RandomForest','Ridge']].sum(axis=1)

# Output the results
selection_df

,Feature,Lasso,GradientBoost,RandomForest,Ridge,Sum
0,Accuracy Rating,1,1,1,1,4
1,Bathrooms,0,0,0,0,0
2,Checkin Rating,0,1,1,1,3
3,Cleanliness Rating,0,1,1,1,3
4,Communication Rating,0,1,1,1,3
5,Location Rating,0,1,1,1,3
6,Overall Rating,1,1,1,1,4
7,Value Rating,0,1,1,1,3
8,Host Response Time,1,1,1,1,4
9,Is Superhost,0,1,1,1,3
10,Neighborhood Group,1,1,1,1,4
11,Is Exact Location,0,1,1,1,3
12,Room Type,0,1,1,1,3
13,Instant Bookable,0,1,1,1,3
14,Accomodates,1,1,1,1,4
15,Bedrooms,1,1,1,1,4
16,Beds,1,1,1,1,4
17,Guests Included,1,1,1,1,4
18,Min Nights,1,1,1,1,4
19,Reviews,1,1,1,1,4
20,Property Type Reduced,1,1,1,1,4
21,Postal Code Reduced,1,1,1,1,4
22,Distance From Center Reduced,0,1,1,1,3
23,Host Since From Now,1,1,1,1,4

In [31]:
selection_df.to_csv('/content/selection_variable_modele.csv')

In [32]:
selection_df.shape

(24, 6)

In [33]:
selection_df[['Feature', 'Sum']].sort_values(by='Sum', ascending=False)

                         Feature  Sum
0                Accuracy Rating    4
6                 Overall Rating    4
18                    Min Nights    4
19                       Reviews    4
15                      Bedrooms    4
14                   Accomodates    4
10            Neighborhood Group    4
8             Host Response Time    4
20         Property Type Reduced    4
21           Postal Code Reduced    4
23           Host Since From Now    4
16                          Beds    4
17               Guests Included    4
3             Cleanliness Rating    3
2                 Checkin Rating    3
5                Location Rating    3
12                     Room Type    3
7                   Value Rating    3
4           Communication Rating    3
11             Is Exact Location    3
9                   Is Superhost    3
13              Instant Bookable    3
22  Distance From Center Reduced    3
1                      Bathrooms    0

In [34]:
selection_df[selection_df['Sum'] >= 3].shape

(23, 6)

In [35]:
#Selecting variables with a sum of selections >= 4
selected_variables = selection_df[selection_df['Sum'] >= 3]['Feature']
selected_variables

0                  Accuracy Rating
2                   Checkin Rating
3               Cleanliness Rating
4             Communication Rating
5                  Location Rating
6                   Overall Rating
7                     Value Rating
8               Host Response Time
9                     Is Superhost
10              Neighborhood Group
11               Is Exact Location
12                       Room Type
13                Instant Bookable
14                     Accomodates
15                        Bedrooms
16                            Beds
17                 Guests Included
18                      Min Nights
19                         Reviews
20           Property Type Reduced
21             Postal Code Reduced
22    Distance From Center Reduced
23             Host Since From Now
Name: Feature, dtype: object

### Creating DataFrame with most valuable variables

In [36]:
df_model = df.loc[:,selected_variables]
df_model['Price'] = df['Price'].copy()

# Output the result to verify
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23536 entries, 0 to 23535
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Accuracy Rating               23536 non-null  float64
 1   Checkin Rating                23536 non-null  float64
 2   Cleanliness Rating            23536 non-null  float64
 3   Communication Rating          23536 non-null  float64
 4   Location Rating               23536 non-null  float64
 5   Overall Rating                23536 non-null  float64
 6   Value Rating                  23536 non-null  float64
 7   Host Response Time            23536 non-null  int64
 8   Is Superhost                  23536 non-null  bool
 9   Neighborhood Group            23536 non-null  int64
 10  Is Exact Location             23536 non-null  bool
 11  Room Type                     23536 non-null  int64
 12  Instant Bookable              23536 non-null  bool
 13  Accomodates                   23536 non-null  float64
 14  Bedrooms                      23536 non-null  float64
 15  Beds                          23536 non-null  float64
 16  Guests Included               23536 non-null  float64
 17  Min Nights                    23536 non-null  float64
 18  Reviews                       23536 non-null  float64
 19  Property Type Reduced         23536 non-null  int64
 20  Postal Code Reduced           23536 non-null  int64
 21  Distance From Center Reduced  23536 non-null  int64
 22  Host Since From Now           23536 non-null  int64
 23  Price                         23536 non-null  float64
dtypes: bool(3), float64(14), int64(7)
memory usage: 3.8 MB

## Store state

In [37]:
selection_df.to_pickle("/content/drive/My Drive/Airbnb/feature_selection_df.pkl")
df_model.to_pickle("/content/drive/My Drive/Airbnb/df_Model_Selection.pkl")